language: node_js
node_js: node
install: npm install
script:
- npm test
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE travis_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: wNsEYVGezOgyH6hWNHJU+yOnQVp0NF1pPm8qJBhW8cWKdkjrRieIO+WaFfvrJHcid/zfJv3m8g5LaPezHaZymdj9Wn4R0V010flZI8Ghkmlikxx07XcU7PPCkiFNkidp5DLFxjsCnB8kKOlAs+JWN80spU270B5Fdpq0v75AimXZ0KnGiDt/tETc3L2VaV7d98lktTxUB2BrBZrLUkho+a8P4YcnGjXQ/sKvf40DjMSNfb6XnEoV0btD3q3ska0dUHgUxwWZCmd8g16UglAdS97PfVnaXCHuR2kr2Kxg4B8/T9wbP58KPiuduk0EzRwvd18Y2vdg8CARz9JNxhPCh1WS+EuEIhhuTTqpMwvB4eOAstT5NWAMsSE4rJxU73H4hM/EUGWbPbu3WWtt5JUDCSyaPRDZ9qCjY/YUGvhwf4ANX7uFEdw35hEZ+Pj5EFlKdP0HHxI7k1i9D9UTOOfQeF4Gq3TXRzYhLmJFrIEttwM0cpHn0riDek5HlZYBpUhHDg8ymhUBA/jd7SoS53kWEZ0Hsdy0zjEl9TYUaxfk/bDgnxE+15cbyVYNZky+vD4uSEWmW5+zfnUxoD9YscOCgIRM38z+GcGkyJeM6QH6dgECsozaNde+VM5CJssw06akxzeavLcw6yKDKW6lnL99MK2gFxBQb6VfVmynGLzl7Wk=
  app: lower-goose-93602
  on:
    repo: Matt-Weiss/quantified-self
