language: node_js
node_js: node
install: npm install
script:
- npm test
deploy:
  api_key:
    secure: OTB9UwSClje1tIHWOu+8C9amaKcKHFHzWIj8tGNo43UDhQsJIeLZbbawvG2w7hNBBMZ1K3QIlrfV2ht9JDiLC4bCVOZbE2bqZ8ee6U+/mqGQIB/7x4CdJDJ+irlgPEcX5v6eiTW8WQcsHB5r2CUCI7o7mvGKrE5F3JPDhiw1qXszjqFdZZKArnaslzeF4hnwKNfeovQU1ELhSt6vmlK3UaHxnhIPCjgEO1rrHC69WOowxHKNr81zLLVe4Yw40jdeAgZ2rzp7aQGNNKYZG4uqEbfnjxo9zX5QtMo1o/sUVmMlni12wjakiixFjg7s/bDN+t0YLrFh9fOfwNaCKqT6pzpLjx3IgBJZh8CvuJH9qdbh7pdCrDeKgDTG5N7SWHFaOosXB4bUfsSDLR82+cn84tCkIu34pxn7LZAgkSuMYsUDqHiJM4TmMoBrXD2OWPXhrklrLpft8EWrtSUCeH+bFnjW2zJVbouclXyNJRbBTZvjLWxHBd0y1oGsY/IuDfQtfCDxnnGJsl892izFlewbfZFvZkqE1jzzfAQQ0rYAib5ljogOjaqzD+rpd/7pjRM5A834Yn1NGV2T66XGX9HNPrm9s2UaBJVuE6R6EkHtJwdJ4QA5+X10zwm3WUO4FsKRiL8SrcYOmq4HhlBPRa1bYjflYtYNFUiy0ZIAnq0/0us=
